// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQr-P09qam6AjxdAT7_JGbeDAVjLXqhmc',
    appId: '1:903836606133:web:97a7be8fb154494d6ea8fc',
    messagingSenderId: '903836606133',
    projectId: 'jobsathi-59f64',
    authDomain: 'jobsathi-59f64.firebaseapp.com',
    storageBucket: 'jobsathi-59f64.appspot.com',
    measurementId: 'G-3F87GGTE1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs5FLvKeAEaXCG2R77i2huCp06y__jZJI',
    appId: '1:903836606133:android:64f61b85d77bc6de6ea8fc',
    messagingSenderId: '903836606133',
    projectId: 'jobsathi-59f64',
    storageBucket: 'jobsathi-59f64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC71Xya4mZWjnFJQWzeFSu_MRQylK5c8yc',
    appId: '1:903836606133:ios:fcea2529922a71716ea8fc',
    messagingSenderId: '903836606133',
    projectId: 'jobsathi-59f64',
    storageBucket: 'jobsathi-59f64.appspot.com',
    iosBundleId: 'com.example.jobSathi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC71Xya4mZWjnFJQWzeFSu_MRQylK5c8yc',
    appId: '1:903836606133:ios:fcea2529922a71716ea8fc',
    messagingSenderId: '903836606133',
    projectId: 'jobsathi-59f64',
    storageBucket: 'jobsathi-59f64.appspot.com',
    iosBundleId: 'com.example.jobSathi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQr-P09qam6AjxdAT7_JGbeDAVjLXqhmc',
    appId: '1:903836606133:web:03b15ab9fc5034276ea8fc',
    messagingSenderId: '903836606133',
    projectId: 'jobsathi-59f64',
    authDomain: 'jobsathi-59f64.firebaseapp.com',
    storageBucket: 'jobsathi-59f64.appspot.com',
    measurementId: 'G-NSREX28G8D',
  );
}
